#include "shell.h"

/**
 * input_buf - Reads and buffers chained commands from the user input.
 * @info: Pointer to the parameter struct.
 * @buf: Address of the buffer to store the input.
 * @len: Address of the length variable for the buffer.
 *
 * This function reads user input from the standard input and buffers it in
 * @buf. If the buffer is empty or exhausted, it refills it by reading from
 * standard input. It handles command chaining, such as separating commands
 * with semicolons (';'). It also removes trailing newlines and comments from
 * the input and maintains a history of commands.
 *
 * Return: The number of bytes read.
 */


ssize_t input_buf(info_t *info, char **buf, size_t *len)
{
	ssize_t x = 0;
	size_t len_p = 0;

	if (!*len)
	{
		free(*buf);
		*buf = NULL;
		signal(SIGINT, sigintHandler);
#if USE_GETLINE
		x = getline(buf, &len_p, stdin);
#else
		x = _getline(info, buf, &len_p);
#endif
		if (x > 0)
		{
			if ((*buf)[x - 1] == '\n')
			{
				(*buf)[x - 1] = '\0';
				x--;
			}
			info->linecount_flag = 1;
			remove_comments(*buf);
			build_history_list(info, *buf, info->histcount++);
			{
				*len = x;
				info->cmd_buf = buf;
			}
		}
	}
	return (x);
}

/**
 * get_input - Gets a line of input from the user.
 * @info: Pointer to the parameter struct.
 *
 * This function retrieves a line of input from the user. It handles command
 * chaining, buffering, and maintains a history of commands.
 *
 * Return: The number of bytes read.
 */

ssize_t get_input(info_t *info)
{
	static char *buf;
	static size_t x, y, l;
	ssize_t s = 0;
	char **buf_p = &(info->arg), *p;

	_putchar(BUF_FLUSH);
	s = input_buf(info, &buf, &l);
	if (s == -1)
		return (-1);
	if (l)
	{
		y = x;
		p = buf + x; /* Get the pointer for return */

		check_chain(info, buf, &y, x, l);
		while (y < l)
		{
			if (is_chain(info, buf, &y))
				break;
			y++;
		}

		x = y + 1; /* This increment past nulled ';'' by 1 */
		if (x >= l)
		{
			x = l = 0; /* This  resets the position and the length */
			info->cmd_buf_type = CMD_NORM;
		}

		*buf_p = p; /* This code pass back the pointer to current command position */
		return (_strlen(p)); /* return length */
	}

	*buf_p = buf;
	return (s); /* Returns the length of buffer from _getline() */
}

/**
 * read_buf - Reads data into a buffer.
 * @info: Pointer to the parameter struct.
 * @buf: The buffer to store the read data.
 * @i: The size of the buffer.
 *
 * This function reads data into a buffer for further processing.
 *
 * Return: The number of bytes read.
 */

ssize_t read_buf(info_t *info, char *buf, size_t *i)
{
	ssize_t s = 0;

	if (*i)
		return (0);
	s = read(info->readfd, buf, READ_BUF_SIZE);
	if (s >= 0)
		*i = s;
	return (s);
}


/**
 * _getline - Reads the next line of input from STDIN.
 * @info: Pointer to the parameter struct.
 * @ptr: Address of the pointer to the buffer.
 * @length: Size of the preallocated buffer if not NULL.
 *
 * This function reads the next line of input from the standard input.
 *
 * Return: The length of the read line.
 */

int _getline(info_t *info, char **ptr, size_t *length)
{
	static char buf[READ_BUF_SIZE];
	static size_t x, l;
	size_t y;
	ssize_t r = 0, s = 0;
	char *p = NULL, *new_p = NULL, *c;

	p = *ptr;
	if (p && length)
		s = *length;
	if (x == l)
		x = l = 0;

	r = read_buf(info, buf, &l);
	if (r == -1 || (r == 0 && l == 0))
		return (-1);

	c = _strchr(buf + x, '\n');
	y = c ? 1 + (unsigned int)(c - buf) : l;
	new_p = _realloc(p, s, s ? s + y : y + 1);
	if (!new_p)
		return (p ? free(p), -1 : -1);

	if (s)
		_strncat(new_p, buf + x, y - x);
	else
		_strncpy(new_p, buf + x, y - x + 1);

	s += y - x;
	x = y;
	p = new_p;

	if (length)
		*length = s;
	*ptr = p;
	return (s);
}

/**
 * sigintHandler - Handles the SIGINT signal (Ctrl-C).
 * @sig_num: The signal number.
 *
 * This function handles the SIGINT signal, which is typically generated by
 * pressing Ctrl-C. It provides a user-friendly response to the interruption.
 */

void sigintHandler(__attribute__((unused))int sig_num)
{
	/* Print a newline to start a new line in the shell output.*/
	_puts("\n");
	/* Display the shell prompt to indicate it's ready for user input. */
	_puts("$ ");
	/* Flush the output buffer to ensure prompt visibility.*/
	_putchar(BUF_FLUSH);
}
